apiVersion: v1
baseDomain: example.cloud
proxy:
  httpProxy: http://<username>:<pswd>@<ip>:<port> 
  httpsProxy: https://<username>:<pswd>@<ip>:<port> 
  noProxy: example.com 
additionalTrustBundle: | 
    -----BEGIN CERTIFICATE-----
    <MY_TRUSTED_CA_CERT>
    -----END CERTIFICATE-----
...
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: hp01
networking:
  clusterNetwork:
  - cidr: 10.186.0.0/16
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.196.0.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.26.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{"auths": ...}'              #-> sera générée avec les prérequis
sshKey: 'ssh-ed25519 AAAA...'             #-> sera générée avec les prérequis

